server:
  port: 9007
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
spring:
  application:
    name: auth
  datasource:
    name: auth_datasource
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shop_auth
    username: root
    password: admin
  redis:
    host: 127.0.0.1
    password: null
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1